version: 2.5.1.{build}
os: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '2.5.1'
  assembly_file_version: '2.5.1'
  assembly_informational_version: '2.5.1'
before_build:
- cmd: nuget restore
build:
  project: linq2db.LINQPad.sln
  verbosity: minimal
after_build:
- cmd: xcopy Source\bin\Release\linq2db.LINQPad.lpx .\ /y

artifacts:
- path: linq2db.LINQPad.lpx
  name: linq2db.LINQPad Driver

deploy:
  provider: FTP
  protocol: ftp
  host: tkachev.com
  username: linq2db
  folder: /
  password:
    secure: rnYQ08pwgvUSkuRhHDndvw==
