version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: linq2db.LINQPad.sln
  verbosity: minimal
artifacts:
- path: Source\bin\Release\linq2db.LINQPad.lpx
  name: linq2db.LINQPad
